name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' # running once a day

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: DoD Forms Management Program scraper
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        wget -e robots=off --user-agent="" https://www.esd.whs.mil/Directives/forms/dd0001_0499/ -O 0001_-_0499.html && wget -e robots=off --user-agent="" https://www.esd.whs.mil/Directives/forms/dd0500_0999/ -O 0500_-_0999.html && wget -e robots=off --user-agent="" https://www.esd.whs.mil/Directives/forms/dd1000_1499/ -O 1000_-_1499.html && wget -e robots=off --user-agent="" https://www.esd.whs.mil/Directives/forms/dd1500_1999/ -O 1500_-_1999.html && wget -e robots=off --user-agent=""  https://www.esd.whs.mil/Directives/forms/dd2000_2499/ -O 2000_-_2499.html && wget -e robots=off --user-agent=""  https://www.esd.whs.mil/Directives/forms/dd2500_2999/ -O 2500_-_2999.html && wget -e robots=off --user-agent=""  https://www.esd.whs.mil/Directives/forms/dd3000_3499/ -O 3000_-_3499.html
    - name: Commit and push if changes detected
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
