name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' # running once a day

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: install w3m
      run: |-
        sudo apt-get install -y w3m
    - name: DoD Forms Management Program scraper
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        wget -e robots=off --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0" https://www.esd.whs.mil/Directives/forms/dd0001_0499/ -O 0001_-_0499.html && wget -e robots=off --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0" https://www.esd.whs.mil/Directives/forms/dd0500_0999/ -O 0500_-_0999.html && wget -e robots=off --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0" https://www.esd.whs.mil/Directives/forms/dd1000_1499/ -O 1000_-_1499.html && wget -e robots=off --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0" https://www.esd.whs.mil/Directives/forms/dd1500_1999/ -O 1500_-_1999.html && wget -e robots=off --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"  https://www.esd.whs.mil/Directives/forms/dd2000_2499/ -O 2000_-_2499.html && wget -e robots=off --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"  https://www.esd.whs.mil/Directives/forms/dd2500_2999/ -O 2500_-_2999.html && wget -e robots=off --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"  https://www.esd.whs.mil/Directives/forms/dd3000_3499/ -O 3000_-_3499.html && w3m -dump https://www.esd.whs.mil/Directives/forms/dd0001_0499/ > 1thru499w3mdump.txt && w3m -dump https://www.esd.whs.mil/Directives/forms/dd0500_0999/ > 500thru999w3mdump.txt && w3m -dump https://www.esd.whs.mil/Directives/forms/dd1000_1499/ > 1000thru1499w3mdump.txt && w3m -dump https://www.esd.whs.mil/Directives/forms/dd1500_1999/ > 1500thru1999w3mdump.txt && w3mdump -dump https://www.esd.whs.mil/Directives/forms/dd2000_2499/ > 2000thru2499w3mdump.txt && w3m -dump https://www.esd.whs.mil/Directives/forms/dd2500_2999/ > 2500thru2999w3mdump.txt && w3m -dump https://www.esd.whs.mil/Directives/forms/dd3000_3499/ > 3000thru3499w3mdump.txt
    - name: Commit and push if changes detected
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
